### ISSUE TITLE
Tag properties do not appear when property has a UI position other than the default e.g. Status

### ISSUE THREAD

**Issue by kerim** [logseq/db-test#47]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

Properties are missing from a page assigned to a class.

### Reproduce the Bug

1 Create the class #cfp ("call for papers")
2. Create a page and assign the #cfp class to the page

### Expected Behavior

All the properties should appear, but only some of them do. Specifically, the "status" and "deadline" properties do not show, even though they are set to show. Adjusting where they show in the property block doesn't help. 

### Screenshots

![Screenshot 2024-09-01 at 11 24 04 AM](https://github.com/user-attachments/assets/ffab1507-8d1a-4af1-9a9f-a4b7e4a64afd)

### Browser, Desktop or Mobile Platform Information

Brave browser on OSX

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by logseq-cldwalker** [comment]
Hi. Good catch. This issue is part of a larger issue on how to display a new tag's properties whose UI position is not the default e.g. left, right or below. We'll need to think about how to fix this for all property types including :default, the type for `Status`.

@tiensonqin  Can confirm this bug by creating a new tag and adding a new :default property to it with choices and setting its position to :block-left. It looks like we're hiding empty positioned properties which is nice ux for tasks but is buggy for any other use of these properties. [Here's a discord feedback thread](https://discord.com/channels/725182569297215569/1279539625559593100/1279539625559593100) asking for :checkbox properties to display when positioned left. What do you think about adding a :hide-empty-positioned-properties? for new tags and only enable it for tasks? That way the tasks ux stays the same and users can interact with empty properties. Multiple empty :block-left properties won't look good as the below screenshot shows but this won't affect tasks with the above proposal and perhaps that's something we solve ux-wise later
<img width="562" alt="Screen Shot 2024-09-02 at 1 04 49 PM" src="https://github.com/user-attachments/assets/58048b0e-1a39-4204-900e-87823f7fc943">

**Comment by logseq-cldwalker** [comment]
@kerim Hi. I think this was fixed by 07a5187e30d0948c3c31213fe98320a9f016ad61. Could you take another look?

**Comment by kerim** [comment]
Status now shows up, but deadline is still missing.

**Comment by kerim** [comment]
![Screenshot 2024-10-19 at 7 43 38 AM](https://github.com/user-attachments/assets/daeb4f6e-1b21-49da-8e26-c52bedbe23b1)
![Screenshot 2024-10-19 at 7 43 10 AM](https://github.com/user-attachments/assets/a7c69ab7-f142-4a90-88b8-ac852810f621)

**Comment by kerim** [comment]
Checked this again. The Deadline property still doesn't show up, even if I set it so that it doesn't hide empty values and isn't hidden by default.

**Comment by kerim** [comment]
Similar issue affected me again. I created the `#timeline` tag and added some properties. Then later went back and added a new property "tags" (built-in option), but this does not show up in the property list for a new block with this tag, no matter how I adjust the settings.

![Screenshot 2025-01-15 at 8 38 18 AM](https://github.com/user-attachments/assets/4186fc43-fb01-46cf-98be-b7cd4ed2a00e)

![Screenshot 2025-01-15 at 8 38 10 AM](https://github.com/user-attachments/assets/04ed527a-5b3a-4a54-abb5-de8b383908e9)

**Comment by kerim** [comment]
Reviewing my issues to see if any can be closed. This issue still remains as described in my last report. Turning off "hide by default" and "hide empty value" has no effect when trying to show a time-date property on a node. Not sure if this is the same as the initial issue led to this issue being opened though. Perhaps it should be split off as a new issue?

**Comment by kerim** [comment]
Tag property management has changed so much, I'm thinking that this issue is probably out of date. I am going to close it for now and re-open only if I encounter the problem again.
